### ISSUE TITLE
Maps page is no longer showing maps

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#61]
![maps](https://cloud.githubusercontent.com/assets/1137878/9898112/01405724-5c50-11e5-832a-c8621d4b6504.png)

**Comment by ldesousa** [comment]
I am having this behaviour with Chromium.

**Comment by uleopold** [comment]
I can confirm this behaviour sometimes for Firefox when the page is loaded for the first time.

**Comment by mdlux** [comment]
Anyway, even when map page is loaded correctly, the list above is appearing as a blink, and then substituted by the map

**Comment by uleopold** [comment]
On Chromium it does not load at all an throws an exception.

![workspace 1_342](https://cloud.githubusercontent.com/assets/1353359/9927696/fee58a18-5d20-11e5-83f3-dd9e77ac15d5.png)

**Comment by uleopold** [comment]
The Chromium and possibly the Firefox exception problem seems to be associated to not being logged in. Once I am logged in. The exception is gone. This can be followed up in #62.

The incorrect loading of the Maps page as described by Luís initially might be related to something else.

**Comment by MStefas** [comment]
I just checked. I confirm that we get this when we are not logged:
![image](https://cloud.githubusercontent.com/assets/7814178/9929766/3f48c5da-5d2f-11e5-9267-7c90a3d55d49.png)

It's due to the use of datasets in the map page, in order to initialize the map to the city we can reach, and also initialize layers in the same way. For now, datasets are obtainable only if you are logged. So there are three possibilities: 

- Test if the user is logged, and if not, initialize the map somewhere, with no layers;
- Give access to some kind of datasets to unlogged users;
- Only allows to reach map page to logged users (I don't think its a good way to fix it);

What do you think ?

**Comment by uleopold** [comment]
I think we should have a common management for all NavBar Tabs what should be shown to the different users and what hidden.

From my point of view it would be good to allow the a non logged in user to all web pages and display what is publicly available to non-logged in users, i.e. 
* Data Manager: published data sets and maps;
* Modules: Registered and published Configured Modules;
* Scenarios: published Scenarios;
* Maps: Published layers;
* About: all; 
* Support: Submission of a Information/contact request.

This will have to be aligned with the concept developed by Matteo, Maël and Luís about the workspace, user  etc. concept.

**Comment by MStefas** [comment]
As layers are currently stored in data sets  I'll check with Matteo the way to do this :)

**Comment by MStefas** [comment]
Should be okay since the last commit
